In [3]:
import pandas as pd

   トマト  キャベツ  レタス  白菜  ほうれん草
0   13     6   11   8      9

In [8]:
import os

def load_order_excel(filename):
  """指定されたファイル名で`order_new/`ディレクトリからExcelファイルを読み込む関数"""
  file_path = os.path.join('/content/order_new', filename)
  try:
    df = pd.read_excel(file_path)
    print(f"{filename} を正常に読み込みました。")
    return df
  except FileNotFoundError:
    print(f"エラー: {file_path} が見つかりません。")
    return None
  except Exception as e:
    print(f"エラー: {filename} の読み込み中に問題が発生しました: {e}")
    return None

load_order_excel('order_A_20230524.xlsx')

order_A_20230524.xlsx を正常に読み込みました。

   トマト  キャベツ  レタス  白菜  ほうれん草
0   13     6   11   8      9

### `order_new`ディレクトリ内のすべてのExcelファイルを読み込む

In [10]:
import os

# `order_new`ディレクトリのパス
order_new_dir = '/content/order_new'

# ディレクトリ内のすべてのファイルを取得
all_files = os.listdir(order_new_dir)

# Excelファイルのみをフィルタリング
excel_files = [f for f in all_files if f.endswith(('.xlsx', '.xls'))]

# 読み込んだDataFrameを格納する辞書
order_dfs = {}

print(f"以下のExcelファイルを読み込みます: {excel_files}")

for filename in excel_files:
  df = load_order_excel(filename)
  if df is not None:
    # ファイル名から拡張子を除いたものをキーとして使用
    key_name = os.path.splitext(filename)[0]
    order_dfs[key_name] = df
    print(f"\n--- {filename} の最初の5行 ---")
    display(df.head())

以下のExcelファイルを読み込みます: ['order_A_20230524.xlsx', 'order_B_20230524.xlsx', 'order_C_20230524.xlsx', 'order_D_20230524.xlsx']
order_A_20230524.xlsx を正常に読み込みました。

--- order_A_20230524.xlsx の最初の5行 ---

   トマト  キャベツ  レタス  白菜  ほうれん草
0   13     6   11   8      9

order_B_20230524.xlsx を正常に読み込みました。

--- order_B_20230524.xlsx の最初の5行 ---

   レタス  白菜  ほうれん草  大根  ニンジン
0   12   8     10   7    13

order_C_20230524.xlsx を正常に読み込みました。

--- order_C_20230524.xlsx の最初の5行 ---

   トマト  レタス  白菜  大根  ニンジン
0    6   11   9   8    12

order_D_20230524.xlsx を正常に読み込みました。

--- order_D_20230524.xlsx の最初の5行 ---

   トマト  キャベツ  レタス  ほうれん草  ニンジン
0   12    15    8      4     7

すべてのDataFrameが`order_dfs`辞書に格納されました。辞書のキーはファイル名（拡張子なし）です。